In [1]:
import gym

from stable_baselines.common.policies import MlpPolicy, CnnPolicy, CnnLstmPolicy
from stable_baselines.common import make_vec_env
from stable_baselines import PPO2


/home/pablo/anaconda3/envs/rl/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/pablo/anaconda3/envs/rl/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/pablo/anaconda3/envs/rl/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/pablo/anaconda3/envs/rl/lib/python3.7/site-packages/ten

In [2]:
agent='CarRacing-v0'
#agent='MountainCar-v0'
#agent='Pendulum-v0'


In [3]:
env0 = gym.make(agent)
print(env0.action_space)
print(env0.observation_space)

Box(3,)
Box(96, 96, 3)


/home/pablo/anaconda3/envs/rl/lib/python3.7/site-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))


In [4]:
try:
    print(env0.action_space.high)
    print(env0.action_space.low)
except:
    print('discrete')
    

[1. 1. 1.]
[-1.  0.  0.]


In [5]:
print(env0.observation_space.high)
print(env0.observation_space.low)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0

In [42]:
env0.close()

In [36]:
# multiprocess environment
paralelo=1

if paralelo==1:
    env1 = gym.make(agent)
else:
    env1 = make_vec_env(agent, n_envs=paralelo)

obs = env1.reset()
print(obs.shape)


/home/pablo/anaconda3/envs/rl/lib/python3.7/site-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))


Track generation: 1252..1569 -> 317-tiles track
(96, 96, 3)


In [37]:
batch=512
updates=1024
cont=True

if not cont:
    model = PPO2(CnnPolicy, env1, verbose=1, n_steps=batch, n_cpu_tf_sess=2)#, cliprange_vf=-1, nminibatches=paralelo)

model.learn(total_timesteps=updates*batch*paralelo)


Track generation: 1358..1702 -> 344-tiles track
------------------------------------
| approxkl           | 30.452763   |
| clipfrac           | 0.6582031   |
| explained_variance | -8.46       |
| fps                | 10          |
| n_updates          | 1           |
| policy_entropy     | 4.414331    |
| policy_loss        | 0.017552488 |
| serial_timesteps   | 512         |
| time_elapsed       | 1.57e-05    |
| total_timesteps    | 512         |
| value_loss         | 395.07672   |
------------------------------------
-----------------------------------
| approxkl           | 0.08196479 |
| clipfrac           | 0.50097656 |
| explained_variance | -5.55      |
| fps                | 10         |
| n_updates          | 2          |
| policy_entropy     | 4.4140873  |
| policy_loss        | 0.05990212 |
| serial_timesteps   | 1024       |
| time_elapsed       | 50.8       |
| total_timesteps    | 1024       |
| value_loss         | 46.911892  |
-----------------------------------
Tra

Track generation: 1208..1514 -> 306-tiles track
-------------------------------------
| approxkl           | 0.014240157  |
| clipfrac           | 0.18310547   |
| explained_variance | -0.105       |
| fps                | 15           |
| n_updates          | 17           |
| policy_entropy     | 4.4317355    |
| policy_loss        | 0.0021607657 |
| serial_timesteps   | 8704         |
| time_elapsed       | 705          |
| total_timesteps    | 8704         |
| value_loss         | 8.872582     |
-------------------------------------
-------------------------------------
| approxkl           | 0.017635195  |
| clipfrac           | 0.2109375    |
| explained_variance | -0.146       |
| fps                | 17           |
| n_updates          | 18           |
| policy_entropy     | 4.4308004    |
| policy_loss        | 0.0026270028 |
| serial_timesteps   | 9216         |
| time_elapsed       | 738          |
| total_timesteps    | 9216         |
| value_loss         | 6.416096     |
--

Track generation: 1027..1287 -> 260-tiles track
------------------------------------
| approxkl           | 0.045055702 |
| clipfrac           | 0.3828125   |
| explained_variance | -0.0789     |
| fps                | 13          |
| n_updates          | 34          |
| policy_entropy     | 4.4588065   |
| policy_loss        | 0.014975373 |
| serial_timesteps   | 17408       |
| time_elapsed       | 1.27e+03    |
| total_timesteps    | 17408       |
| value_loss         | 3.2178822   |
------------------------------------
-------------------------------------
| approxkl           | 0.011777905  |
| clipfrac           | 0.18017578   |
| explained_variance | -0.0905      |
| fps                | 13           |
| n_updates          | 35           |
| policy_entropy     | 4.456581     |
| policy_loss        | 0.0032206597 |
| serial_timesteps   | 17920        |
| time_elapsed       | 1.31e+03     |
| total_timesteps    | 17920        |
| value_loss         | 2.4624813    |
---------------

Track generation: 1153..1445 -> 292-tiles track
-------------------------------------
| approxkl           | 0.008882951  |
| clipfrac           | 0.12158203   |
| explained_variance | -0.0214      |
| fps                | 13           |
| n_updates          | 50           |
| policy_entropy     | 4.4637012    |
| policy_loss        | 0.0050643366 |
| serial_timesteps   | 25600        |
| time_elapsed       | 1.85e+03     |
| total_timesteps    | 25600        |
| value_loss         | 0.85508907   |
-------------------------------------
-------------------------------------
| approxkl           | 0.012355244  |
| clipfrac           | 0.171875     |
| explained_variance | -0.569       |
| fps                | 13           |
| n_updates          | 51           |
| policy_entropy     | 4.468322     |
| policy_loss        | -0.009069932 |
| serial_timesteps   | 26112        |
| time_elapsed       | 1.89e+03     |
| total_timesteps    | 26112        |
| value_loss         | 0.7299202    |
--

Track generation: 1281..1611 -> 330-tiles track
-------------------------------------
| approxkl           | 0.017538609  |
| clipfrac           | 0.22753906   |
| explained_variance | -0.0394      |
| fps                | 16           |
| n_updates          | 66           |
| policy_entropy     | 4.486857     |
| policy_loss        | 0.0026749824 |
| serial_timesteps   | 33792        |
| time_elapsed       | 2.4e+03      |
| total_timesteps    | 33792        |
| value_loss         | 0.7196504    |
-------------------------------------
------------------------------------
| approxkl           | 0.017567186 |
| clipfrac           | 0.234375    |
| explained_variance | -2.69       |
| fps                | 13          |
| n_updates          | 67          |
| policy_entropy     | 4.4891324   |
| policy_loss        | 0.005292004 |
| serial_timesteps   | 34304       |
| time_elapsed       | 2.43e+03    |
| total_timesteps    | 34304       |
| value_loss         | 0.09722427  |
--------------

--------------------------------------
| approxkl           | 0.02099402    |
| clipfrac           | 0.24658203    |
| explained_variance | -0.109        |
| fps                | 16            |
| n_updates          | 82            |
| policy_entropy     | 4.4896255     |
| policy_loss        | -0.0035294998 |
| serial_timesteps   | 41984         |
| time_elapsed       | 2.96e+03      |
| total_timesteps    | 41984         |
| value_loss         | 0.2813874     |
--------------------------------------
Track generation: 1231..1543 -> 312-tiles track
-------------------------------------
| approxkl           | 0.005800298  |
| clipfrac           | 0.06689453   |
| explained_variance | -0.0221      |
| fps                | 15           |
| n_updates          | 83           |
| policy_entropy     | 4.486447     |
| policy_loss        | 0.0012961677 |
| serial_timesteps   | 42496        |
| time_elapsed       | 3e+03        |
| total_timesteps    | 42496        |
| value_loss         | 0.65

--------------------------------------
| approxkl           | 0.011540543   |
| clipfrac           | 0.1743164     |
| explained_variance | -0.109        |
| fps                | 17            |
| n_updates          | 98            |
| policy_entropy     | 4.490996      |
| policy_loss        | -0.0061569726 |
| serial_timesteps   | 50176         |
| time_elapsed       | 3.45e+03      |
| total_timesteps    | 50176         |
| value_loss         | 0.10494408    |
--------------------------------------
Track generation: 1235..1548 -> 313-tiles track
-------------------------------------
| approxkl           | 0.023362568  |
| clipfrac           | 0.2602539    |
| explained_variance | -0.0342      |
| fps                | 16           |
| n_updates          | 99           |
| policy_entropy     | 4.4879503    |
| policy_loss        | 0.0051548206 |
| serial_timesteps   | 50688        |
| time_elapsed       | 3.48e+03     |
| total_timesteps    | 50688        |
| value_loss         | 0.82

Track generation: 1027..1295 -> 268-tiles track
-------------------------------------
| approxkl           | 0.017291842  |
| clipfrac           | 0.20751953   |
| explained_variance | -0.0167      |
| fps                | 17           |
| n_updates          | 114          |
| policy_entropy     | 4.4826145    |
| policy_loss        | 0.0049640685 |
| serial_timesteps   | 58368        |
| time_elapsed       | 3.93e+03     |
| total_timesteps    | 58368        |
| value_loss         | 1.0222712    |
-------------------------------------
-------------------------------------
| approxkl           | 0.011263203  |
| clipfrac           | 0.15673828   |
| explained_variance | -0.00827     |
| fps                | 16           |
| n_updates          | 115          |
| policy_entropy     | 4.4825797    |
| policy_loss        | -0.004314065 |
| serial_timesteps   | 58880        |
| time_elapsed       | 3.96e+03     |
| total_timesteps    | 58880        |
| value_loss         | 0.21232425   |
--

Track generation: 1353..1695 -> 342-tiles track
-------------------------------------
| approxkl           | 0.017320648  |
| clipfrac           | 0.24365234   |
| explained_variance | 0.00101      |
| fps                | 15           |
| n_updates          | 130          |
| policy_entropy     | 4.488359     |
| policy_loss        | -0.001216313 |
| serial_timesteps   | 66560        |
| time_elapsed       | 4.41e+03     |
| total_timesteps    | 66560        |
| value_loss         | 1.1571437    |
-------------------------------------
--------------------------------------
| approxkl           | 0.02038607    |
| clipfrac           | 0.2524414     |
| explained_variance | -0.0177       |
| fps                | 17            |
| n_updates          | 131           |
| policy_entropy     | 4.488678      |
| policy_loss        | -0.0018239262 |
| serial_timesteps   | 67072         |
| time_elapsed       | 4.44e+03      |
| total_timesteps    | 67072         |
| value_loss         | 0.0880

Track generation: 1080..1354 -> 274-tiles track
------------------------------------
| approxkl           | 0.012984612 |
| clipfrac           | 0.16259766  |
| explained_variance | -0.0137     |
| fps                | 16          |
| n_updates          | 146         |
| policy_entropy     | 4.4954767   |
| policy_loss        | 0.005837296 |
| serial_timesteps   | 74752       |
| time_elapsed       | 4.89e+03    |
| total_timesteps    | 74752       |
| value_loss         | 0.8653581   |
------------------------------------
------------------------------------
| approxkl           | 0.019248517 |
| clipfrac           | 0.22998047  |
| explained_variance | -0.179      |
| fps                | 16          |
| n_updates          | 147         |
| policy_entropy     | 4.4953685   |
| policy_loss        | 0.010962259 |
| serial_timesteps   | 75264       |
| time_elapsed       | 4.92e+03    |
| total_timesteps    | 75264       |
| value_loss         | 0.037349526 |
---------------------------

-------------------------------------
| approxkl           | 0.012407344  |
| clipfrac           | 0.16894531   |
| explained_variance | -0.139       |
| fps                | 16           |
| n_updates          | 162          |
| policy_entropy     | 4.492888     |
| policy_loss        | 0.0012673724 |
| serial_timesteps   | 82944        |
| time_elapsed       | 5.36e+03     |
| total_timesteps    | 82944        |
| value_loss         | 0.12098651   |
-------------------------------------
Track generation: 1060..1329 -> 269-tiles track
------------------------------------
| approxkl           | 0.015662296 |
| clipfrac           | 0.20507812  |
| explained_variance | -0.0178     |
| fps                | 17          |
| n_updates          | 163         |
| policy_entropy     | 4.493145    |
| policy_loss        | 0.008573217 |
| serial_timesteps   | 83456       |
| time_elapsed       | 5.39e+03    |
| total_timesteps    | 83456       |
| value_loss         | 0.82650286  |
--------------

------------------------------------
| approxkl           | 0.04047104  |
| clipfrac           | 0.3984375   |
| explained_variance | -0.0564     |
| fps                | 18          |
| n_updates          | 178         |
| policy_entropy     | 4.4846005   |
| policy_loss        | 0.017910682 |
| serial_timesteps   | 91136       |
| time_elapsed       | 5.85e+03    |
| total_timesteps    | 91136       |
| value_loss         | 0.12679219  |
------------------------------------
Track generation: 1188..1494 -> 306-tiles track
------------------------------------
| approxkl           | 0.034559943 |
| clipfrac           | 0.33740234  |
| explained_variance | -0.00729    |
| fps                | 17          |
| n_updates          | 179         |
| policy_entropy     | 4.4826064   |
| policy_loss        | 0.024414208 |
| serial_timesteps   | 91648       |
| time_elapsed       | 5.87e+03    |
| total_timesteps    | 91648       |
| value_loss         | 1.1309723   |
---------------------------

Track generation: 1192..1494 -> 302-tiles track
--------------------------------------
| approxkl           | 0.011997096   |
| clipfrac           | 0.1640625     |
| explained_variance | -0.0125       |
| fps                | 18            |
| n_updates          | 194           |
| policy_entropy     | 4.479289      |
| policy_loss        | 0.00075611426 |
| serial_timesteps   | 99328         |
| time_elapsed       | 6.32e+03      |
| total_timesteps    | 99328         |
| value_loss         | 0.6542017     |
--------------------------------------
--------------------------------------
| approxkl           | 0.015090432   |
| clipfrac           | 0.19335938    |
| explained_variance | -0.0165       |
| fps                | 16            |
| n_updates          | 195           |
| policy_entropy     | 4.481357      |
| policy_loss        | -0.0026652832 |
| serial_timesteps   | 99840         |
| time_elapsed       | 6.35e+03      |
| total_timesteps    | 99840         |
| value_loss    

Track generation: 1152..1444 -> 292-tiles track
-------------------------------------
| approxkl           | 0.011904385  |
| clipfrac           | 0.17578125   |
| explained_variance | -0.00621     |
| fps                | 17           |
| n_updates          | 210          |
| policy_entropy     | 4.4851875    |
| policy_loss        | -0.003246142 |
| serial_timesteps   | 107520       |
| time_elapsed       | 6.8e+03      |
| total_timesteps    | 107520       |
| value_loss         | 0.8305765    |
-------------------------------------
------------------------------------
| approxkl           | 0.022570431 |
| clipfrac           | 0.27783203  |
| explained_variance | -0.00198    |
| fps                | 16          |
| n_updates          | 211         |
| policy_entropy     | 4.4841204   |
| policy_loss        | 0.010782756 |
| serial_timesteps   | 108032      |
| time_elapsed       | 6.83e+03    |
| total_timesteps    | 108032      |
| value_loss         | 0.25237915  |
--------------

Track generation: 1140..1429 -> 289-tiles track
--------------------------------------
| approxkl           | 0.019103011   |
| clipfrac           | 0.22753906    |
| explained_variance | -0.0148       |
| fps                | 16            |
| n_updates          | 226           |
| policy_entropy     | 4.4890866     |
| policy_loss        | -0.0058526546 |
| serial_timesteps   | 115712        |
| time_elapsed       | 7.28e+03      |
| total_timesteps    | 115712        |
| value_loss         | 0.8874831     |
--------------------------------------
-------------------------------------
| approxkl           | 0.009719826  |
| clipfrac           | 0.123535156  |
| explained_variance | -0.00832     |
| fps                | 16           |
| n_updates          | 227          |
| policy_entropy     | 4.4888515    |
| policy_loss        | 0.0020135334 |
| serial_timesteps   | 116224       |
| time_elapsed       | 7.31e+03     |
| total_timesteps    | 116224       |
| value_loss         | 0.26

--------------------------------------
| approxkl           | 0.016659219   |
| clipfrac           | 0.22998047    |
| explained_variance | -0.0408       |
| fps                | 15            |
| n_updates          | 242           |
| policy_entropy     | 4.4855604     |
| policy_loss        | -0.0046311826 |
| serial_timesteps   | 123904        |
| time_elapsed       | 7.77e+03      |
| total_timesteps    | 123904        |
| value_loss         | 0.18863581    |
--------------------------------------
Track generation: 1247..1563 -> 316-tiles track
------------------------------------
| approxkl           | 0.009555162 |
| clipfrac           | 0.14501953  |
| explained_variance | -0.00772    |
| fps                | 16          |
| n_updates          | 243         |
| policy_entropy     | 4.4844093   |
| policy_loss        | 0.002743505 |
| serial_timesteps   | 124416      |
| time_elapsed       | 7.8e+03     |
| total_timesteps    | 124416      |
| value_loss         | 0.6325272   |
-

------------------------------------
| approxkl           | 0.024812423 |
| clipfrac           | 0.2553711   |
| explained_variance | 0.00482     |
| fps                | 16          |
| n_updates          | 258         |
| policy_entropy     | 4.4952474   |
| policy_loss        | 0.010328632 |
| serial_timesteps   | 132096      |
| time_elapsed       | 8.25e+03    |
| total_timesteps    | 132096      |
| value_loss         | 0.19185604  |
------------------------------------
Track generation: 1356..1699 -> 343-tiles track
-------------------------------------
| approxkl           | 0.014434539  |
| clipfrac           | 0.1743164    |
| explained_variance | -0.0119      |
| fps                | 17           |
| n_updates          | 259          |
| policy_entropy     | 4.4927893    |
| policy_loss        | -0.001397254 |
| serial_timesteps   | 132608       |
| time_elapsed       | 8.28e+03     |
| total_timesteps    | 132608       |
| value_loss         | 1.1748435    |
---------------

-------------------------------------
| approxkl           | 0.01948336   |
| clipfrac           | 0.23242188   |
| explained_variance | -0.00898     |
| fps                | 17           |
| n_updates          | 274          |
| policy_entropy     | 4.4957275    |
| policy_loss        | -0.004605867 |
| serial_timesteps   | 140288       |
| time_elapsed       | 8.73e+03     |
| total_timesteps    | 140288       |
| value_loss         | 0.3430813    |
-------------------------------------
Track generation: 1207..1513 -> 306-tiles track
-------------------------------------
| approxkl           | 0.015486123  |
| clipfrac           | 0.1616211    |
| explained_variance | -0.0045      |
| fps                | 16           |
| n_updates          | 275          |
| policy_entropy     | 4.497567     |
| policy_loss        | 0.0052040834 |
| serial_timesteps   | 140800       |
| time_elapsed       | 8.76e+03     |
| total_timesteps    | 140800       |
| value_loss         | 0.71878856   |
--

Track generation: 1130..1417 -> 287-tiles track
-------------------------------------
| approxkl           | 0.009928914  |
| clipfrac           | 0.14111328   |
| explained_variance | -0.0245      |
| fps                | 17           |
| n_updates          | 290          |
| policy_entropy     | 4.489908     |
| policy_loss        | 0.0011523865 |
| serial_timesteps   | 148480       |
| time_elapsed       | 9.21e+03     |
| total_timesteps    | 148480       |
| value_loss         | 0.9284999    |
-------------------------------------
-------------------------------------
| approxkl           | 0.015187765  |
| clipfrac           | 0.19677734   |
| explained_variance | -0.0332      |
| fps                | 17           |
| n_updates          | 291          |
| policy_entropy     | 4.4918575    |
| policy_loss        | 0.0007910589 |
| serial_timesteps   | 148992       |
| time_elapsed       | 9.24e+03     |
| total_timesteps    | 148992       |
| value_loss         | 0.27191684   |
--

Track generation: 1078..1358 -> 280-tiles track
-------------------------------------
| approxkl           | 0.012104214  |
| clipfrac           | 0.15576172   |
| explained_variance | -0.00637     |
| fps                | 8            |
| n_updates          | 306          |
| policy_entropy     | 4.4842787    |
| policy_loss        | 0.0027111853 |
| serial_timesteps   | 156672       |
| time_elapsed       | 3.18e+04     |
| total_timesteps    | 156672       |
| value_loss         | 0.95665795   |
-------------------------------------
------------------------------------
| approxkl           | 0.019296326 |
| clipfrac           | 0.2368164   |
| explained_variance | -0.00266    |
| fps                | 8           |
| n_updates          | 307         |
| policy_entropy     | 4.4886155   |
| policy_loss        | 0.015031084 |
| serial_timesteps   | 157184      |
| time_elapsed       | 3.18e+04    |
| total_timesteps    | 157184      |
| value_loss         | 1.6000911   |
--------------

-------------------------------------
| approxkl           | 0.032080967  |
| clipfrac           | 0.33789062   |
| explained_variance | -0.00397     |
| fps                | 14           |
| n_updates          | 322          |
| policy_entropy     | 4.473041     |
| policy_loss        | 0.0051082745 |
| serial_timesteps   | 164864       |
| time_elapsed       | 3.25e+04     |
| total_timesteps    | 164864       |
| value_loss         | 0.5117355    |
-------------------------------------
Track generation: 1174..1480 -> 306-tiles track
--------------------------------------
| approxkl           | 0.007998437   |
| clipfrac           | 0.10888672    |
| explained_variance | -0.00603      |
| fps                | 12            |
| n_updates          | 323           |
| policy_entropy     | 4.470648      |
| policy_loss        | -0.0028634067 |
| serial_timesteps   | 165376        |
| time_elapsed       | 3.25e+04      |
| total_timesteps    | 165376        |
| value_loss         | 1.3125

--------------------------------------
| approxkl           | 0.017153822   |
| clipfrac           | 0.22460938    |
| explained_variance | 0.00348       |
| fps                | 12            |
| n_updates          | 338           |
| policy_entropy     | 4.461915      |
| policy_loss        | -0.0044095237 |
| serial_timesteps   | 173056        |
| time_elapsed       | 3.31e+04      |
| total_timesteps    | 173056        |
| value_loss         | 0.40968335    |
--------------------------------------
Track generation: 1132..1419 -> 287-tiles track
--------------------------------------
| approxkl           | 0.021165267   |
| clipfrac           | 0.24023438    |
| explained_variance | -0.000827     |
| fps                | 12            |
| n_updates          | 339           |
| policy_entropy     | 4.459829      |
| policy_loss        | -0.0001958182 |
| serial_timesteps   | 173568        |
| time_elapsed       | 3.32e+04      |
| total_timesteps    | 173568        |
| value_loss    

-------------------------------------
| approxkl           | 0.005719178  |
| clipfrac           | 0.06982422   |
| explained_variance | -0.00637     |
| fps                | 12           |
| n_updates          | 354          |
| policy_entropy     | 4.4757915    |
| policy_loss        | 0.0012940866 |
| serial_timesteps   | 181248       |
| time_elapsed       | 3.38e+04     |
| total_timesteps    | 181248       |
| value_loss         | 0.47567856   |
-------------------------------------
Track generation: 1171..1468 -> 297-tiles track
------------------------------------
| approxkl           | 0.024244405 |
| clipfrac           | 0.2709961   |
| explained_variance | -0.00529    |
| fps                | 12          |
| n_updates          | 355         |
| policy_entropy     | 4.4747596   |
| policy_loss        | 0.015468482 |
| serial_timesteps   | 181760      |
| time_elapsed       | 3.38e+04    |
| total_timesteps    | 181760      |
| value_loss         | 1.5859066   |
--------------

Track generation: 967..1218 -> 251-tiles track
retry to generate track (normal if there are not many of this messages)
Track generation: 1168..1464 -> 296-tiles track
------------------------------------
| approxkl           | 0.02694877  |
| clipfrac           | 0.29589844  |
| explained_variance | 0.0017      |
| fps                | 12          |
| n_updates          | 370         |
| policy_entropy     | 4.4751153   |
| policy_loss        | 0.018123629 |
| serial_timesteps   | 189440      |
| time_elapsed       | 3.44e+04    |
| total_timesteps    | 189440      |
| value_loss         | 2.4195828   |
------------------------------------
-------------------------------------
| approxkl           | 0.013285993  |
| clipfrac           | 0.17773438   |
| explained_variance | -0.00209     |
| fps                | 12           |
| n_updates          | 371          |
| policy_entropy     | 4.4750886    |
| policy_loss        | 0.0037037358 |
| serial_timesteps   | 189952       |
| time_ela

Track generation: 1039..1302 -> 263-tiles track
------------------------------------
| approxkl           | 0.015616153 |
| clipfrac           | 0.18554688  |
| explained_variance | -0.00795    |
| fps                | 12          |
| n_updates          | 386         |
| policy_entropy     | 4.4574957   |
| policy_loss        | 0.006700946 |
| serial_timesteps   | 197632      |
| time_elapsed       | 3.51e+04    |
| total_timesteps    | 197632      |
| value_loss         | 1.4776354   |
------------------------------------
-------------------------------------
| approxkl           | 0.00727675   |
| clipfrac           | 0.10546875   |
| explained_variance | -2.2         |
| fps                | 12           |
| n_updates          | 387          |
| policy_entropy     | 4.4567556    |
| policy_loss        | 0.0004624133 |
| serial_timesteps   | 198144       |
| time_elapsed       | 3.51e+04     |
| total_timesteps    | 198144       |
| value_loss         | 0.15842253   |
---------------

Track generation: 1304..1634 -> 330-tiles track
--------------------------------------
| approxkl           | 0.010321258   |
| clipfrac           | 0.1459961     |
| explained_variance | -0.0275       |
| fps                | 11            |
| n_updates          | 402           |
| policy_entropy     | 4.467134      |
| policy_loss        | 0.00060423475 |
| serial_timesteps   | 205824        |
| time_elapsed       | 3.58e+04      |
| total_timesteps    | 205824        |
| value_loss         | 0.83333063    |
--------------------------------------
Track generation: 1148..1439 -> 291-tiles track
--------------------------------------
| approxkl           | 0.023220852   |
| clipfrac           | 0.25878906    |
| explained_variance | -0.00152      |
| fps                | 11            |
| n_updates          | 403           |
| policy_entropy     | 4.4711504     |
| policy_loss        | -0.0036891396 |
| serial_timesteps   | 206336        |
| time_elapsed       | 3.58e+04      |
| total

-------------------------------------
| approxkl           | 0.015500516  |
| clipfrac           | 0.203125     |
| explained_variance | -3.45        |
| fps                | 16           |
| n_updates          | 418          |
| policy_entropy     | 4.455387     |
| policy_loss        | 0.0020545442 |
| serial_timesteps   | 214016       |
| time_elapsed       | 3.63e+04     |
| total_timesteps    | 214016       |
| value_loss         | 0.09658499   |
-------------------------------------
Track generation: 1132..1419 -> 287-tiles track
--------------------------------------
| approxkl           | 0.010742959   |
| clipfrac           | 0.15283203    |
| explained_variance | -0.00779      |
| fps                | 15            |
| n_updates          | 419           |
| policy_entropy     | 4.4554896     |
| policy_loss        | -0.0009351892 |
| serial_timesteps   | 214528        |
| time_elapsed       | 3.64e+04      |
| total_timesteps    | 214528        |
| value_loss         | 1.0115

--------------------------------------
| approxkl           | 0.007684735   |
| clipfrac           | 0.10058594    |
| explained_variance | -0.00699      |
| fps                | 14            |
| n_updates          | 434           |
| policy_entropy     | 4.449629      |
| policy_loss        | -0.0020487404 |
| serial_timesteps   | 222208        |
| time_elapsed       | 3.69e+04      |
| total_timesteps    | 222208        |
| value_loss         | 0.93657446    |
--------------------------------------
Track generation: 1195..1498 -> 303-tiles track
--------------------------------------
| approxkl           | 0.0060021365  |
| clipfrac           | 0.08154297    |
| explained_variance | -0.00459      |
| fps                | 14            |
| n_updates          | 435           |
| policy_entropy     | 4.447181      |
| policy_loss        | 0.00035197937 |
| serial_timesteps   | 222720        |
| time_elapsed       | 3.69e+04      |
| total_timesteps    | 222720        |
| value_loss    

Track generation: 1019..1277 -> 258-tiles track
-------------------------------------
| approxkl           | 0.015532702  |
| clipfrac           | 0.21386719   |
| explained_variance | -0.00275     |
| fps                | 14           |
| n_updates          | 450          |
| policy_entropy     | 4.4462824    |
| policy_loss        | -0.010811783 |
| serial_timesteps   | 230400       |
| time_elapsed       | 3.74e+04     |
| total_timesteps    | 230400       |
| value_loss         | 0.9751624    |
-------------------------------------
-------------------------------------
| approxkl           | 0.0067148614 |
| clipfrac           | 0.08691406   |
| explained_variance | 0.000211     |
| fps                | 16           |
| n_updates          | 451          |
| policy_entropy     | 4.4452486    |
| policy_loss        | -0.002535596 |
| serial_timesteps   | 230912       |
| time_elapsed       | 3.75e+04     |
| total_timesteps    | 230912       |
| value_loss         | 0.6558969    |
--

Track generation: 1279..1603 -> 324-tiles track
------------------------------------
| approxkl           | 0.023884553 |
| clipfrac           | 0.28857422  |
| explained_variance | -0.00089    |
| fps                | 15          |
| n_updates          | 466         |
| policy_entropy     | 4.441311    |
| policy_loss        | 0.005888056 |
| serial_timesteps   | 238592      |
| time_elapsed       | 3.8e+04     |
| total_timesteps    | 238592      |
| value_loss         | 0.6887198   |
------------------------------------
---------------------------------------
| approxkl           | 0.01215276     |
| clipfrac           | 0.17285156     |
| explained_variance | -0.00822       |
| fps                | 21             |
| n_updates          | 467            |
| policy_entropy     | 4.44201        |
| policy_loss        | -0.00065335503 |
| serial_timesteps   | 239104         |
| time_elapsed       | 3.8e+04        |
| total_timesteps    | 239104         |
| value_loss         | 0.168875

Track generation: 1293..1626 -> 333-tiles track
--------------------------------------
| approxkl           | 0.013738811   |
| clipfrac           | 0.17675781    |
| explained_variance | 0.015         |
| fps                | 23            |
| n_updates          | 482           |
| policy_entropy     | 4.4597206     |
| policy_loss        | -0.0045840926 |
| serial_timesteps   | 246784        |
| time_elapsed       | 3.83e+04      |
| total_timesteps    | 246784        |
| value_loss         | 0.6679638     |
--------------------------------------
-------------------------------------
| approxkl           | 0.020765182  |
| clipfrac           | 0.21484375   |
| explained_variance | -0.0243      |
| fps                | 22           |
| n_updates          | 483          |
| policy_entropy     | 4.4616365    |
| policy_loss        | 0.0047835167 |
| serial_timesteps   | 247296       |
| time_elapsed       | 3.84e+04     |
| total_timesteps    | 247296       |
| value_loss         | 0.15

-------------------------------------
| approxkl           | 0.007954723  |
| clipfrac           | 0.11669922   |
| explained_variance | -0.00497     |
| fps                | 31           |
| n_updates          | 498          |
| policy_entropy     | 4.475489     |
| policy_loss        | -0.004675586 |
| serial_timesteps   | 254976       |
| time_elapsed       | 3.87e+04     |
| total_timesteps    | 254976       |
| value_loss         | 0.20952931   |
-------------------------------------
Track generation: 1369..1715 -> 346-tiles track
---------------------------------------
| approxkl           | 0.013526857    |
| clipfrac           | 0.1694336      |
| explained_variance | -0.00664       |
| fps                | 29             |
| n_updates          | 499            |
| policy_entropy     | 4.477327       |
| policy_loss        | -0.00039474922 |
| serial_timesteps   | 255488         |
| time_elapsed       | 3.87e+04       |
| total_timesteps    | 255488         |
| value_loss      

-------------------------------------
| approxkl           | 0.016697006  |
| clipfrac           | 0.21240234   |
| explained_variance | -0.0117      |
| fps                | 29           |
| n_updates          | 514          |
| policy_entropy     | 4.4816065    |
| policy_loss        | 0.0032983955 |
| serial_timesteps   | 263168       |
| time_elapsed       | 3.9e+04      |
| total_timesteps    | 263168       |
| value_loss         | 0.73827875   |
-------------------------------------
Track generation: 1289..1615 -> 326-tiles track
--------------------------------------
| approxkl           | 0.012518833   |
| clipfrac           | 0.17480469    |
| explained_variance | -0.0128       |
| fps                | 23            |
| n_updates          | 515           |
| policy_entropy     | 4.4811826     |
| policy_loss        | -0.0011379224 |
| serial_timesteps   | 263680        |
| time_elapsed       | 3.9e+04       |
| total_timesteps    | 263680        |
| value_loss         | 1.2746

Track generation: 1169..1446 -> 277-tiles track
retry to generate track (normal if there are not many of this messages)
Track generation: 1083..1358 -> 275-tiles track
--------------------------------------
| approxkl           | 0.017702881   |
| clipfrac           | 0.22216797    |
| explained_variance | -0.000557     |
| fps                | 24            |
| n_updates          | 530           |
| policy_entropy     | 4.4739466     |
| policy_loss        | -0.0034881132 |
| serial_timesteps   | 271360        |
| time_elapsed       | 3.93e+04      |
| total_timesteps    | 271360        |
| value_loss         | 1.1327044     |
--------------------------------------
------------------------------------
| approxkl           | 0.029241795 |
| clipfrac           | 0.29492188  |
| explained_variance | -0.000747   |
| fps                | 28          |
| n_updates          | 531         |
| policy_entropy     | 4.475098    |
| policy_loss        | 0.021189684 |
| serial_timesteps   | 271872

Track generation: 1162..1461 -> 299-tiles track
------------------------------------
| approxkl           | 0.028125478 |
| clipfrac           | 0.23388672  |
| explained_variance | -0.00874    |
| fps                | 23          |
| n_updates          | 546         |
| policy_entropy     | 4.4709187   |
| policy_loss        | 0.019225508 |
| serial_timesteps   | 279552      |
| time_elapsed       | 3.96e+04    |
| total_timesteps    | 279552      |
| value_loss         | 1.7154219   |
------------------------------------
------------------------------------
| approxkl           | 0.05213781  |
| clipfrac           | 0.36328125  |
| explained_variance | -0.698      |
| fps                | 26          |
| n_updates          | 547         |
| policy_entropy     | 4.468808    |
| policy_loss        | 0.008221097 |
| serial_timesteps   | 280064      |
| time_elapsed       | 3.97e+04    |
| total_timesteps    | 280064      |
| value_loss         | 0.17239237  |
---------------------------

Track generation: 1382..1732 -> 350-tiles track
------------------------------------
| approxkl           | 0.008938707 |
| clipfrac           | 0.11669922  |
| explained_variance | -0.023      |
| fps                | 18          |
| n_updates          | 562         |
| policy_entropy     | 4.444968    |
| policy_loss        | -0.00523491 |
| serial_timesteps   | 287744      |
| time_elapsed       | 4e+04       |
| total_timesteps    | 287744      |
| value_loss         | 0.6557351   |
------------------------------------
-------------------------------------
| approxkl           | 0.015600708  |
| clipfrac           | 0.1899414    |
| explained_variance | -1.45        |
| fps                | 16           |
| n_updates          | 563          |
| policy_entropy     | 4.4448085    |
| policy_loss        | 0.0054362495 |
| serial_timesteps   | 288256       |
| time_elapsed       | 4e+04        |
| total_timesteps    | 288256       |
| value_loss         | 0.068387985  |
---------------

Track generation: 1179..1478 -> 299-tiles track
-------------------------------------
| approxkl           | 0.020914506  |
| clipfrac           | 0.26611328   |
| explained_variance | 0.0023       |
| fps                | 10           |
| n_updates          | 577          |
| policy_entropy     | 4.452007     |
| policy_loss        | 0.0039932546 |
| serial_timesteps   | 295424       |
| time_elapsed       | 4.04e+04     |
| total_timesteps    | 295424       |
| value_loss         | 0.612073     |
-------------------------------------
-------------------------------------
| approxkl           | 0.01286127   |
| clipfrac           | 0.15673828   |
| explained_variance | -0.0048      |
| fps                | 9            |
| n_updates          | 578          |
| policy_entropy     | 4.450285     |
| policy_loss        | -0.007710909 |
| serial_timesteps   | 295936       |
| time_elapsed       | 4.05e+04     |
| total_timesteps    | 295936       |
| value_loss         | 0.71205413   |
--

Track generation: 1176..1474 -> 298-tiles track
-------------------------------------
| approxkl           | 0.015381564  |
| clipfrac           | 0.20947266   |
| explained_variance | -0.00134     |
| fps                | 16           |
| n_updates          | 593          |
| policy_entropy     | 4.456877     |
| policy_loss        | 0.0016021482 |
| serial_timesteps   | 303616       |
| time_elapsed       | 4.1e+04      |
| total_timesteps    | 303616       |
| value_loss         | 0.9201342    |
-------------------------------------
------------------------------------
| approxkl           | 0.020697637 |
| clipfrac           | 0.24560547  |
| explained_variance | -0.576      |
| fps                | 13          |
| n_updates          | 594         |
| policy_entropy     | 4.456359    |
| policy_loss        | 0.0047418   |
| serial_timesteps   | 304128      |
| time_elapsed       | 4.11e+04    |
| total_timesteps    | 304128      |
| value_loss         | 0.08682404  |
--------------

Track generation: 1196..1504 -> 308-tiles track
--------------------------------------
| approxkl           | 0.009441983   |
| clipfrac           | 0.11328125    |
| explained_variance | -0.0115       |
| fps                | 20            |
| n_updates          | 609           |
| policy_entropy     | 4.4507813     |
| policy_loss        | -0.0017642402 |
| serial_timesteps   | 311808        |
| time_elapsed       | 4.16e+04      |
| total_timesteps    | 311808        |
| value_loss         | 1.4914917     |
--------------------------------------
-------------------------------------
| approxkl           | 0.016273681  |
| clipfrac           | 0.21289062   |
| explained_variance | -4.72        |
| fps                | 19           |
| n_updates          | 610          |
| policy_entropy     | 4.4504905    |
| policy_loss        | 0.0026341255 |
| serial_timesteps   | 312320       |
| time_elapsed       | 4.16e+04     |
| total_timesteps    | 312320       |
| value_loss         | 0.02

---------------------------------------
| approxkl           | 0.006915952    |
| clipfrac           | 0.09863281     |
| explained_variance | -3.93          |
| fps                | 17             |
| n_updates          | 625            |
| policy_entropy     | 4.455283       |
| policy_loss        | -0.00021195435 |
| serial_timesteps   | 320000         |
| time_elapsed       | 4.21e+04       |
| total_timesteps    | 320000         |
| value_loss         | 0.015992438    |
---------------------------------------
Track generation: 1066..1339 -> 273-tiles track
retry to generate track (normal if there are not many of this messages)
Track generation: 1003..1261 -> 258-tiles track
retry to generate track (normal if there are not many of this messages)
Track generation: 1152..1444 -> 292-tiles track
-------------------------------------
| approxkl           | 0.016972624  |
| clipfrac           | 0.21728516   |
| explained_variance | 0.00222      |
| fps                | 19           |
| 

------------------------------------
| approxkl           | 0.041908927 |
| clipfrac           | 0.2763672   |
| explained_variance | -0.00533    |
| fps                | 20          |
| n_updates          | 641         |
| policy_entropy     | 4.459252    |
| policy_loss        | 0.009683934 |
| serial_timesteps   | 328192      |
| time_elapsed       | 4.26e+04    |
| total_timesteps    | 328192      |
| value_loss         | 0.077917434 |
------------------------------------
Track generation: 1200..1504 -> 304-tiles track
------------------------------------
| approxkl           | 0.04897492  |
| clipfrac           | 0.37060547  |
| explained_variance | 0.00624     |
| fps                | 19          |
| n_updates          | 642         |
| policy_entropy     | 4.4619303   |
| policy_loss        | 0.010792902 |
| serial_timesteps   | 328704      |
| time_elapsed       | 4.26e+04    |
| total_timesteps    | 328704      |
| value_loss         | 0.9692243   |
---------------------------

Track generation: 1058..1333 -> 275-tiles track
------------------------------------
| approxkl           | 0.027923804 |
| clipfrac           | 0.31640625  |
| explained_variance | -0.00136    |
| fps                | 19          |
| n_updates          | 657         |
| policy_entropy     | 4.447851    |
| policy_loss        | 0.01801715  |
| serial_timesteps   | 336384      |
| time_elapsed       | 4.3e+04     |
| total_timesteps    | 336384      |
| value_loss         | 1.0085608   |
------------------------------------
-------------------------------------
| approxkl           | 0.031938374  |
| clipfrac           | 0.30371094   |
| explained_variance | -0.0198      |
| fps                | 19           |
| n_updates          | 658          |
| policy_entropy     | 4.446969     |
| policy_loss        | 0.0018099397 |
| serial_timesteps   | 336896       |
| time_elapsed       | 4.3e+04      |
| total_timesteps    | 336896       |
| value_loss         | 0.10935403   |
---------------

Track generation: 1192..1500 -> 308-tiles track
------------------------------------
| approxkl           | 0.025933206 |
| clipfrac           | 0.28222656  |
| explained_variance | -0.0108     |
| fps                | 15          |
| n_updates          | 673         |
| policy_entropy     | 4.4482613   |
| policy_loss        | 0.013185617 |
| serial_timesteps   | 344576      |
| time_elapsed       | 4.35e+04    |
| total_timesteps    | 344576      |
| value_loss         | 0.8364104   |
------------------------------------
-------------------------------------
| approxkl           | 0.007973609  |
| clipfrac           | 0.10205078   |
| explained_variance | -0.00224     |
| fps                | 14           |
| n_updates          | 674          |
| policy_entropy     | 4.450471     |
| policy_loss        | 0.0028099879 |
| serial_timesteps   | 345088       |
| time_elapsed       | 4.35e+04     |
| total_timesteps    | 345088       |
| value_loss         | 1.1022483    |
---------------

Track generation: 1192..1494 -> 302-tiles track
------------------------------------
| approxkl           | 0.021994716 |
| clipfrac           | 0.2734375   |
| explained_variance | 0.00199     |
| fps                | 15          |
| n_updates          | 689         |
| policy_entropy     | 4.46744     |
| policy_loss        | 0.012287159 |
| serial_timesteps   | 352768      |
| time_elapsed       | 4.4e+04     |
| total_timesteps    | 352768      |
| value_loss         | 0.9717977   |
------------------------------------
------------------------------------
| approxkl           | 0.01383762  |
| clipfrac           | 0.1772461   |
| explained_variance | -5.19       |
| fps                | 17          |
| n_updates          | 690         |
| policy_entropy     | 4.467275    |
| policy_loss        | 0.006329748 |
| serial_timesteps   | 353280      |
| time_elapsed       | 4.41e+04    |
| total_timesteps    | 353280      |
| value_loss         | 0.021799121 |
---------------------------

-------------------------------------
| approxkl           | 0.020166723  |
| clipfrac           | 0.24169922   |
| explained_variance | -0.00109     |
| fps                | 15           |
| n_updates          | 705          |
| policy_entropy     | 4.4735713    |
| policy_loss        | 0.0038527632 |
| serial_timesteps   | 360960       |
| time_elapsed       | 4.45e+04     |
| total_timesteps    | 360960       |
| value_loss         | 0.66471857   |
-------------------------------------
Track generation: 1064..1334 -> 270-tiles track
-------------------------------------
| approxkl           | 0.023868663  |
| clipfrac           | 0.25683594   |
| explained_variance | 0.00122      |
| fps                | 15           |
| n_updates          | 706          |
| policy_entropy     | 4.4755163    |
| policy_loss        | 0.0077233524 |
| serial_timesteps   | 361472       |
| time_elapsed       | 4.45e+04     |
| total_timesteps    | 361472       |
| value_loss         | 1.901479     |
--

--------------------------------------
| approxkl           | 0.00880461    |
| clipfrac           | 0.12597656    |
| explained_variance | -0.904        |
| fps                | 17            |
| n_updates          | 721           |
| policy_entropy     | 4.481086      |
| policy_loss        | -0.0031114127 |
| serial_timesteps   | 369152        |
| time_elapsed       | 4.5e+04       |
| total_timesteps    | 369152        |
| value_loss         | 0.07854805    |
--------------------------------------
Track generation: 1235..1548 -> 313-tiles track
-------------------------------------
| approxkl           | 0.0206104    |
| clipfrac           | 0.26123047   |
| explained_variance | -0.000514    |
| fps                | 19           |
| n_updates          | 722          |
| policy_entropy     | 4.4791703    |
| policy_loss        | 0.0024475134 |
| serial_timesteps   | 369664       |
| time_elapsed       | 4.5e+04      |
| total_timesteps    | 369664       |
| value_loss         | 0.75

Track generation: 1191..1494 -> 303-tiles track
--------------------------------------
| approxkl           | 0.014859976   |
| clipfrac           | 0.18603516    |
| explained_variance | 0.000491      |
| fps                | 18            |
| n_updates          | 737           |
| policy_entropy     | 4.4603133     |
| policy_loss        | 0.00068167376 |
| serial_timesteps   | 377344        |
| time_elapsed       | 4.54e+04      |
| total_timesteps    | 377344        |
| value_loss         | 5.6899343     |
--------------------------------------
--------------------------------------
| approxkl           | 0.008217152   |
| clipfrac           | 0.10449219    |
| explained_variance | -0.00102      |
| fps                | 19            |
| n_updates          | 738           |
| policy_entropy     | 4.460847      |
| policy_loss        | 2.6709167e-06 |
| serial_timesteps   | 377856        |
| time_elapsed       | 4.54e+04      |
| total_timesteps    | 377856        |
| value_loss    

Track generation: 1064..1335 -> 271-tiles track
retry to generate track (normal if there are not many of this messages)
Track generation: 1146..1436 -> 290-tiles track
-------------------------------------
| approxkl           | 0.016973965  |
| clipfrac           | 0.22851562   |
| explained_variance | -0.0154      |
| fps                | 18           |
| n_updates          | 753          |
| policy_entropy     | 4.4618106    |
| policy_loss        | 0.0007506981 |
| serial_timesteps   | 385536       |
| time_elapsed       | 4.58e+04     |
| total_timesteps    | 385536       |
| value_loss         | 0.70481235   |
-------------------------------------
-------------------------------------
| approxkl           | 0.010743704  |
| clipfrac           | 0.14257812   |
| explained_variance | -1.45        |
| fps                | 18           |
| n_updates          | 754          |
| policy_entropy     | 4.4580154    |
| policy_loss        | 3.545935e-05 |
| serial_timesteps   | 386048     

Track generation: 1171..1468 -> 297-tiles track
--------------------------------------
| approxkl           | 0.011401065   |
| clipfrac           | 0.15966797    |
| explained_variance | -0.000339     |
| fps                | 20            |
| n_updates          | 769           |
| policy_entropy     | 4.454214      |
| policy_loss        | -0.0012528915 |
| serial_timesteps   | 393728        |
| time_elapsed       | 4.63e+04      |
| total_timesteps    | 393728        |
| value_loss         | 1.6579376     |
--------------------------------------
--------------------------------------
| approxkl           | 0.015864888   |
| clipfrac           | 0.21875       |
| explained_variance | -0.00533      |
| fps                | 20            |
| n_updates          | 770           |
| policy_entropy     | 4.4527497     |
| policy_loss        | -0.0031531136 |
| serial_timesteps   | 394240        |
| time_elapsed       | 4.63e+04      |
| total_timesteps    | 394240        |
| value_loss    

------------------------------------
| approxkl           | 0.009696911 |
| clipfrac           | 0.119628906 |
| explained_variance | -0.0185     |
| fps                | 19          |
| n_updates          | 785         |
| policy_entropy     | 4.4389434   |
| policy_loss        | 0.003785806 |
| serial_timesteps   | 401920      |
| time_elapsed       | 4.67e+04    |
| total_timesteps    | 401920      |
| value_loss         | 0.4496867   |
------------------------------------
Track generation: 1131..1418 -> 287-tiles track
------------------------------------
| approxkl           | 0.019402955 |
| clipfrac           | 0.21142578  |
| explained_variance | -0.00288    |
| fps                | 19          |
| n_updates          | 786         |
| policy_entropy     | 4.44168     |
| policy_loss        | 0.008325178 |
| serial_timesteps   | 402432      |
| time_elapsed       | 4.67e+04    |
| total_timesteps    | 402432      |
| value_loss         | 0.79460967  |
---------------------------

-------------------------------------
| approxkl           | 0.019685041  |
| clipfrac           | 0.22363281   |
| explained_variance | -5.79        |
| fps                | 20           |
| n_updates          | 801          |
| policy_entropy     | 4.4470882    |
| policy_loss        | -0.010325013 |
| serial_timesteps   | 410112       |
| time_elapsed       | 4.71e+04     |
| total_timesteps    | 410112       |
| value_loss         | 0.039918803  |
-------------------------------------
Track generation: 1378..1730 -> 352-tiles track
retry to generate track (normal if there are not many of this messages)
Track generation: 1128..1419 -> 291-tiles track
--------------------------------------
| approxkl           | 0.019426849   |
| clipfrac           | 0.20214844    |
| explained_variance | -0.00949      |
| fps                | 20            |
| n_updates          | 802           |
| policy_entropy     | 4.44688       |
| policy_loss        | -0.0015589135 |
| serial_timesteps   | 410

--------------------------------------
| approxkl           | 0.0147437835  |
| clipfrac           | 0.21142578    |
| explained_variance | -3.58         |
| fps                | 19            |
| n_updates          | 817           |
| policy_entropy     | 4.4525795     |
| policy_loss        | -7.106224e-05 |
| serial_timesteps   | 418304        |
| time_elapsed       | 4.75e+04      |
| total_timesteps    | 418304        |
| value_loss         | 0.012040382   |
--------------------------------------
Track generation: 1050..1319 -> 269-tiles track
retry to generate track (normal if there are not many of this messages)
Track generation: 1329..1674 -> 345-tiles track
---------------------------------------
| approxkl           | 0.011142632    |
| clipfrac           | 0.14697266     |
| explained_variance | 0.00393        |
| fps                | 19             |
| n_updates          | 818            |
| policy_entropy     | 4.453913       |
| policy_loss        | -0.00086619635 |
| ser

Track generation: 1132..1419 -> 287-tiles track
--------------------------------------
| approxkl           | 0.014628773   |
| clipfrac           | 0.20458984    |
| explained_variance | -0.00414      |
| fps                | 20            |
| n_updates          | 833           |
| policy_entropy     | 4.4473186     |
| policy_loss        | -0.0030768297 |
| serial_timesteps   | 426496        |
| time_elapsed       | 4.79e+04      |
| total_timesteps    | 426496        |
| value_loss         | 1.0711551     |
--------------------------------------
--------------------------------------
| approxkl           | 0.013436279   |
| clipfrac           | 0.17871094    |
| explained_variance | -0.00261      |
| fps                | 20            |
| n_updates          | 834           |
| policy_entropy     | 4.4425974     |
| policy_loss        | -0.0062012943 |
| serial_timesteps   | 427008        |
| time_elapsed       | 4.8e+04       |
| total_timesteps    | 427008        |
| value_loss    

Track generation: 1146..1437 -> 291-tiles track
--------------------------------------
| approxkl           | 0.014314925   |
| clipfrac           | 0.1743164     |
| explained_variance | -0.00415      |
| fps                | 19            |
| n_updates          | 849           |
| policy_entropy     | 4.443302      |
| policy_loss        | 0.00038475893 |
| serial_timesteps   | 434688        |
| time_elapsed       | 4.84e+04      |
| total_timesteps    | 434688        |
| value_loss         | 1.4924957     |
--------------------------------------
-------------------------------------
| approxkl           | 0.030156862  |
| clipfrac           | 0.29248047   |
| explained_variance | -0.00989     |
| fps                | 19           |
| n_updates          | 850          |
| policy_entropy     | 4.440823     |
| policy_loss        | 0.0009623016 |
| serial_timesteps   | 435200       |
| time_elapsed       | 4.84e+04     |
| total_timesteps    | 435200       |
| value_loss         | 0.63

------------------------------------
| approxkl           | 0.02221481  |
| clipfrac           | 0.20898438  |
| explained_variance | 0.0089      |
| fps                | 24          |
| n_updates          | 865         |
| policy_entropy     | 4.434547    |
| policy_loss        | 0.016938161 |
| serial_timesteps   | 442880      |
| time_elapsed       | 5.01e+04    |
| total_timesteps    | 442880      |
| value_loss         | 0.6967027   |
------------------------------------
Track generation: 1173..1471 -> 298-tiles track
------------------------------------
| approxkl           | 0.013582027 |
| clipfrac           | 0.16992188  |
| explained_variance | 0.00319     |
| fps                | 27          |
| n_updates          | 866         |
| policy_entropy     | 4.435773    |
| policy_loss        | 0.003155911 |
| serial_timesteps   | 443392      |
| time_elapsed       | 5.01e+04    |
| total_timesteps    | 443392      |
| value_loss         | 0.9968532   |
---------------------------

Track generation: 1211..1520 -> 309-tiles track
-------------------------------------
| approxkl           | 0.010603395  |
| clipfrac           | 0.1508789    |
| explained_variance | 0.00701      |
| fps                | 23           |
| n_updates          | 882          |
| policy_entropy     | 4.4367895    |
| policy_loss        | 0.0022613017 |
| serial_timesteps   | 451584       |
| time_elapsed       | 5.05e+04     |
| total_timesteps    | 451584       |
| value_loss         | 0.812049     |
-------------------------------------
--------------------------------------
| approxkl           | 0.017494284   |
| clipfrac           | 0.21582031    |
| explained_variance | -3.31         |
| fps                | 23            |
| n_updates          | 883           |
| policy_entropy     | 4.4395103     |
| policy_loss        | -0.0065209433 |
| serial_timesteps   | 452096        |
| time_elapsed       | 5.05e+04      |
| total_timesteps    | 452096        |
| value_loss         | 0.0171

Track generation: 996..1249 -> 253-tiles track
--------------------------------------
| approxkl           | 0.013238881   |
| clipfrac           | 0.18115234    |
| explained_variance | -0.0208       |
| fps                | 24            |
| n_updates          | 898           |
| policy_entropy     | 4.4400086     |
| policy_loss        | -0.0043307883 |
| serial_timesteps   | 459776        |
| time_elapsed       | 5.09e+04      |
| total_timesteps    | 459776        |
| value_loss         | 1.0835255     |
--------------------------------------
--------------------------------------
| approxkl           | 0.015596791   |
| clipfrac           | 0.20800781    |
| explained_variance | -9.47         |
| fps                | 24            |
| n_updates          | 899           |
| policy_entropy     | 4.440669      |
| policy_loss        | -0.0044707097 |
| serial_timesteps   | 460288        |
| time_elapsed       | 5.09e+04      |
| total_timesteps    | 460288        |
| value_loss     

--------------------------------------
| approxkl           | 0.009147631   |
| clipfrac           | 0.11767578    |
| explained_variance | -18.7         |
| fps                | 22            |
| n_updates          | 914           |
| policy_entropy     | 4.4464774     |
| policy_loss        | 0.00082544703 |
| serial_timesteps   | 467968        |
| time_elapsed       | 5.12e+04      |
| total_timesteps    | 467968        |
| value_loss         | 0.012594924   |
--------------------------------------
Track generation: 1029..1293 -> 264-tiles track
retry to generate track (normal if there are not many of this messages)
Track generation: 1172..1468 -> 296-tiles track
--------------------------------------
| approxkl           | 0.01833679    |
| clipfrac           | 0.24316406    |
| explained_variance | -0.0116       |
| fps                | 19            |
| n_updates          | 915           |
| policy_entropy     | 4.446806      |
| policy_loss        | -0.0010890726 |
| serial_time

--------------------------------------
| approxkl           | 0.012206176   |
| clipfrac           | 0.16210938    |
| explained_variance | -10.2         |
| fps                | 21            |
| n_updates          | 930           |
| policy_entropy     | 4.4538746     |
| policy_loss        | -0.0069826925 |
| serial_timesteps   | 476160        |
| time_elapsed       | 5.16e+04      |
| total_timesteps    | 476160        |
| value_loss         | 0.0071309153  |
--------------------------------------
Track generation: 1124..1409 -> 285-tiles track
------------------------------------
| approxkl           | 0.011698816 |
| clipfrac           | 0.14697266  |
| explained_variance | -0.0139     |
| fps                | 23          |
| n_updates          | 931         |
| policy_entropy     | 4.453128    |
| policy_loss        | 0.002364745 |
| serial_timesteps   | 476672      |
| time_elapsed       | 5.16e+04    |
| total_timesteps    | 476672      |
| value_loss         | 0.99056333  |
-

Track generation: 1188..1489 -> 301-tiles track
--------------------------------------
| approxkl           | 0.011637865   |
| clipfrac           | 0.1665039     |
| explained_variance | 0.00143       |
| fps                | 21            |
| n_updates          | 946           |
| policy_entropy     | 4.4628553     |
| policy_loss        | -0.0012277066 |
| serial_timesteps   | 484352        |
| time_elapsed       | 5.19e+04      |
| total_timesteps    | 484352        |
| value_loss         | 0.75380474    |
--------------------------------------
-------------------------------------
| approxkl           | 0.009202818  |
| clipfrac           | 0.12792969   |
| explained_variance | 0.00102      |
| fps                | 21           |
| n_updates          | 947          |
| policy_entropy     | 4.4619956    |
| policy_loss        | -0.004298964 |
| serial_timesteps   | 484864       |
| time_elapsed       | 5.19e+04     |
| total_timesteps    | 484864       |
| value_loss         | 0.26

Track generation: 1134..1427 -> 293-tiles track
------------------------------------
| approxkl           | 0.012293573 |
| clipfrac           | 0.17041016  |
| explained_variance | 0.000257    |
| fps                | 22          |
| n_updates          | 962         |
| policy_entropy     | 4.4533744   |
| policy_loss        | 0.008056734 |
| serial_timesteps   | 492544      |
| time_elapsed       | 5.23e+04    |
| total_timesteps    | 492544      |
| value_loss         | 0.9072305   |
------------------------------------
--------------------------------------
| approxkl           | 0.009205758   |
| clipfrac           | 0.12646484    |
| explained_variance | -0.000213     |
| fps                | 24            |
| n_updates          | 963           |
| policy_entropy     | 4.4545956     |
| policy_loss        | -5.079538e-05 |
| serial_timesteps   | 493056        |
| time_elapsed       | 5.23e+04      |
| total_timesteps    | 493056        |
| value_loss         | 0.7992006     |
---

Track generation: 1127..1413 -> 286-tiles track
------------------------------------
| approxkl           | 0.040542282 |
| clipfrac           | 0.35107422  |
| explained_variance | -0.00258    |
| fps                | 23          |
| n_updates          | 978         |
| policy_entropy     | 4.471986    |
| policy_loss        | 0.026591336 |
| serial_timesteps   | 500736      |
| time_elapsed       | 5.26e+04    |
| total_timesteps    | 500736      |
| value_loss         | 1.2491003   |
------------------------------------
-------------------------------------
| approxkl           | 0.010921636  |
| clipfrac           | 0.1352539    |
| explained_variance | -0.0228      |
| fps                | 24           |
| n_updates          | 979          |
| policy_entropy     | 4.4714375    |
| policy_loss        | -0.003103608 |
| serial_timesteps   | 501248       |
| time_elapsed       | 5.27e+04     |
| total_timesteps    | 501248       |
| value_loss         | 0.25703803   |
---------------

------------------------------------
| approxkl           | 0.011521727 |
| clipfrac           | 0.15332031  |
| explained_variance | -0.000804   |
| fps                | 22          |
| n_updates          | 994         |
| policy_entropy     | 4.4741135   |
| policy_loss        | -0.00244405 |
| serial_timesteps   | 508928      |
| time_elapsed       | 5.3e+04     |
| total_timesteps    | 508928      |
| value_loss         | 0.6758236   |
------------------------------------
Track generation: 1383..1733 -> 350-tiles track
--------------------------------------
| approxkl           | 0.007400229   |
| clipfrac           | 0.09472656    |
| explained_variance | 0.00141       |
| fps                | 19            |
| n_updates          | 995           |
| policy_entropy     | 4.4765096     |
| policy_loss        | -9.518745e-05 |
| serial_timesteps   | 509440        |
| time_elapsed       | 5.3e+04       |
| total_timesteps    | 509440        |
| value_loss         | 0.85579956    |
---

---------------------------------------
| approxkl           | 0.0057921987   |
| clipfrac           | 0.075683594    |
| explained_variance | -0.00281       |
| fps                | 22             |
| n_updates          | 1010           |
| policy_entropy     | 4.481092       |
| policy_loss        | -0.00045239204 |
| serial_timesteps   | 517120         |
| time_elapsed       | 5.34e+04       |
| total_timesteps    | 517120         |
| value_loss         | 0.57403827     |
---------------------------------------
Track generation: 1060..1338 -> 278-tiles track
------------------------------------
| approxkl           | 0.013458892 |
| clipfrac           | 0.17578125  |
| explained_variance | -0.00601    |
| fps                | 24          |
| n_updates          | 1011        |
| policy_entropy     | 4.484005    |
| policy_loss        | 0.006941447 |
| serial_timesteps   | 517632      |
| time_elapsed       | 5.34e+04    |
| total_timesteps    | 517632      |
| value_loss         | 1.

In [38]:
import pickle

model.save("ppo2_cnn_agentII", cloudpickle=True)
param_list=model.get_parameter_list()
param=model.get_parameters()

f = open("ppo2_cnn_agentII_param.pkl","wb")
#pickle.dump(param_list,f)
pickle.dump(param,f)
f.close()

env1.close()

In [48]:
# Enjoy trained agent
env2 = gym.make(agent)

if paralelo==1:
    obs=env2.reset()
else:
    import numpy as np
    obs=np.empty([paralelo,96,96,3])
    for i in range(paralelo):
        obs[i,:,:,:] = env2.reset()

        
done = False
pasos = 0
_states=None

while not done and pasos<1000:
    action, _states = model.predict(obs,_states)
    obs, reward, done, info = env2.step(action)
    env2.render()
    pasos+=1

    
env2.close()

Track generation: 1155..1448 -> 293-tiles track


KeyboardInterrupt: 

In [45]:
print(reward, done, info, pasos)

-0.10000000000000142 False {} 691


In [46]:
print(action, _states)

[-1.  0.  0.] None


In [47]:
obs.shape

(96, 96, 3)

In [44]:
env2.close()