In [1]:
import gym

from stable_baselines.common.policies import MlpPolicy, CnnPolicy, CnnLstmPolicy, CnnLnLstmPolicy
from stable_baselines.common import make_vec_env
from stable_baselines import PPO2


/home/pablo/anaconda3/envs/rl/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/pablo/anaconda3/envs/rl/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/pablo/anaconda3/envs/rl/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/pablo/anaconda3/envs/rl/lib/python3.7/site-packages/ten

In [2]:
agent='CarRacing-v0'
#agent='MountainCar-v0'
#agent='Pendulum-v0'


In [3]:
env0 = gym.make(agent)
print(env0.action_space)
print(env0.observation_space)

Box(3,)
Box(96, 96, 3)


/home/pablo/anaconda3/envs/rl/lib/python3.7/site-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))


In [4]:
try:
    print(env0.action_space.high)
    print(env0.action_space.low)
except:
    print('discrete')
    

[1. 1. 1.]
[-1.  0.  0.]


In [5]:
print(env0.observation_space.high)
print(env0.observation_space.low)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0

In [6]:
env0.close()

In [7]:
# multiprocess environment
paralelo=1

if paralelo==1:
    env1 = gym.make(agent)
else:
    env1 = make_vec_env(agent, n_envs=paralelo)

obs = env1.reset()
print(obs.shape)


Track generation: 1306..1637 -> 331-tiles track
(96, 96, 3)


In [ ]:
batch=1000
updates=300
cont=False

if not cont:
    model = PPO2(CnnLstmPolicy, env1, verbose=1, n_steps=batch, n_cpu_tf_sess=2, nminibatches=paralelo) 
    #, max_grad_norm=1)
    #model = PPO2(CnnLstmPolicy, env1, verbose=1, n_steps=batch, n_cpu_tf_sess=2, nminibatches=paralelo)

model.learn(total_timesteps=updates*batch*paralelo)


Wrapping the env in a DummyVecEnv.






Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


Track generation: 1316..1649 -> 333-tiles track
Track generation: 1107..1395 -> 288-tiles track
-------------------------------------
| approxkl           | 0.007719477  |
| clipfrac           | 0.10475      |
| explained_variance | 0.0106       |
| fps                | 2            |
| n_updates          | 1            |
| policy_entropy     | 4.255829     |
| policy_loss        | 0.0010256412 |
| serial_timesteps   | 1000         |
| time_elapsed       | 2.29e-05     |
| total_timesteps    | 1000         |
| value_loss         | 0.84020686   |
-------------------------------------
Track generation: 1082..1362 -> 280-tiles track
---------------------------------------
| approxkl           | 0.0014625798   |
| clipfrac           | 0.00825        |
| explained_variance | 0.017          |
| fps                | 16             |
| n_updates          | 2 

Track generation: 1187..1488 -> 301-tiles track
--------------------------------------
| approxkl           | 0.003223439   |
| clipfrac           | 0.04          |
| explained_variance | 0.142         |
| fps                | 13            |
| n_updates          | 12            |
| policy_entropy     | 4.2490077     |
| policy_loss        | -0.0014798334 |
| serial_timesteps   | 12000         |
| time_elapsed       | 1.06e+03      |
| total_timesteps    | 12000         |
| value_loss         | 0.62467194    |
--------------------------------------
Track generation: 1042..1307 -> 265-tiles track
-------------------------------------
| approxkl           | 0.001079117  |
| clipfrac           | 0.0045       |
| explained_variance | 0.199        |
| fps                | 13           |
| n_updates          | 13           |
| policy_entropy     | 4.249405     |
| policy_loss        | -0.001105998 |
| serial_timesteps   | 13000        |
| time_elapsed       | 1.14e+03     |
| total_timesteps

Track generation: 1176..1474 -> 298-tiles track
-------------------------------------
| approxkl           | 0.015355838  |
| clipfrac           | 0.18724999   |
| explained_variance | 0.731        |
| fps                | 13           |
| n_updates          | 27           |
| policy_entropy     | 4.2474995    |
| policy_loss        | 0.0010855023 |
| serial_timesteps   | 27000        |
| time_elapsed       | 2.19e+03     |
| total_timesteps    | 27000        |
| value_loss         | 1.5959752    |
-------------------------------------
Track generation: 1192..1494 -> 302-tiles track
--------------------------------------
| approxkl           | 0.011796161   |
| clipfrac           | 0.1515        |
| explained_variance | 0.628         |
| fps                | 14            |
| n_updates          | 28            |
| policy_entropy     | 4.2469845     |
| policy_loss        | -0.0030746092 |
| serial_timesteps   | 28000         |
| time_elapsed       | 2.26e+03      |
| total_timesteps   

Track generation: 1077..1351 -> 274-tiles track
--------------------------------------
| approxkl           | 0.0063403994  |
| clipfrac           | 0.089499995   |
| explained_variance | 0.602         |
| fps                | 13            |
| n_updates          | 42            |
| policy_entropy     | 4.2455573     |
| policy_loss        | -0.0043597324 |
| serial_timesteps   | 42000         |
| time_elapsed       | 3.28e+03      |
| total_timesteps    | 42000         |
| value_loss         | 0.4819444     |
--------------------------------------
Track generation: 1209..1515 -> 306-tiles track
-------------------------------------
| approxkl           | 0.01284712   |
| clipfrac           | 0.1825       |
| explained_variance | 0.409        |
| fps                | 14           |
| n_updates          | 43           |
| policy_entropy     | 4.2458067    |
| policy_loss        | 0.0018750073 |
| serial_timesteps   | 43000        |
| time_elapsed       | 3.36e+03     |
| total_timesteps

-------------------------------------
| approxkl           | 0.011348491  |
| clipfrac           | 0.162        |
| explained_variance | 0.709        |
| fps                | 13           |
| n_updates          | 57           |
| policy_entropy     | 4.246951     |
| policy_loss        | 0.0060468214 |
| serial_timesteps   | 57000        |
| time_elapsed       | 4.4e+03      |
| total_timesteps    | 57000        |
| value_loss         | 2.037076     |
-------------------------------------
Track generation: 1224..1534 -> 310-tiles track
-------------------------------------
| approxkl           | 0.00857779   |
| clipfrac           | 0.1215       |
| explained_variance | 0.715        |
| fps                | 14           |
| n_updates          | 58           |
| policy_entropy     | 4.2469354    |
| policy_loss        | 0.0012125755 |
| serial_timesteps   | 58000        |
| time_elapsed       | 4.47e+03     |
| total_timesteps    | 58000        |
| value_loss         | 0.48252833   |
--

In [1]:
param=model.get_parameters()


NameError: name 'model' is not defined

In [ ]:
import pickle
file='ppo2_gym_lstm_bs1000'

model.save(file, cloudpickle=True)
param_list=model.get_parameter_list()
param=model.get_parameters()

f = open(file+'_param.pkl',"wb")
#pickle.dump(param_list,f)
pickle.dump(param,f)
f.close()
env1.close()

In [ ]:
# Enjoy trained agent
env2 = gym.make(agent)

if paralelo==1:
    obs=env2.reset()
else:
    import numpy as np
    obs=np.empty([paralelo,96,96,3])
    for i in range(paralelo):
        obs[i,:,:,:] = env2.reset()

        
done = False
pasos = 0
_states=None

while not done and pasos<1000:
    action, _states = model.predict(obs,_states)
    obs, reward, done, info = env2.step(action)
    env2.render()
    pasos+=1

    
env2.close()

In [ ]:
print(reward, done, info, pasos)

In [ ]:
print(action, _states)

In [ ]:
obs.shape

In [ ]:
env2.close()