In [1]:
import gym

In [2]:
agent='CarRacing-v0'
#agent='MountainCar-v0'
#agent='Pendulum-v0'

In [3]:
env0 = gym.make(agent)
print(env0.action_space)
print(env0.observation_space)

Discrete(5)
Box(96, 96, 3)


In [4]:
try:
    print(env0.action_space.high)
    print(env0.action_space.low)
except:
    print('discrete')
    print(env0.action_space.sample())
    

discrete
4


In [5]:
print(env0.observation_space.high)
print(env0.observation_space.low)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0

In [6]:
env0.close()

In [7]:
from stable_baselines.common.policies import CnnPolicy, CnnLstmPolicy, CnnLnLstmPolicy
from stable_baselines.common.vec_env import DummyVecEnv
from stable_baselines.common import make_vec_env
from stable_baselines import PPO2 #, PPO1


/home/pablo/anaconda3/envs/ppo/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/pablo/anaconda3/envs/ppo/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/pablo/anaconda3/envs/ppo/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/pablo/anaconda3/envs/ppo/lib/python3.7/site-packages

In [8]:
# multiprocess environment
paralelo=1

if paralelo==1:
    env1 = gym.make(agent)
else:
    env1 = make_vec_env(agent, n_envs=paralelo)

obs = env1.reset()
print(obs.shape)

Track generation: 1187..1488 -> 301-tiles track
(96, 96, 3)


In [ ]:
batch=1000
updates=250
cont=False

if not cont:
    model = PPO2(CnnLstmPolicy, env1, verbose=1, n_steps=batch, n_cpu_tf_sess=2, nminibatches=paralelo) 
    #, max_grad_norm=1)
    #model = PPO2(CnnLstmPolicy, env1, verbose=1, n_steps=batch, n_cpu_tf_sess=2, nminibatches=paralelo)

model.learn(total_timesteps=updates*batch*paralelo)


Wrapping the env in a DummyVecEnv.






Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


Track generation: 1131..1418 -> 287-tiles track
done by time
Track generation: 1253..1570 -> 317-tiles track
done by time
Track generation: 1204..1509 -> 305-tiles track
done by time
Track generation: 1122..1407 -> 285-tiles track


In [ ]:
import pickle
file='ppo2_v0_mike_lstm_4f_bs1000'

model.save(file, cloudpickle=True)
param_list=model.get_parameter_list()
param=model.get_parameters()

f = open(file+'_param.pkl',"wb")
#pickle.dump(param_list,f)
pickle.dump(param,f)
f.close()

In [ ]:
#batch=512
updates=250
cont=True

if not cont:
    model = PPO2(CnnLstmPolicy, env1, verbose=1, n_steps=batch, n_cpu_tf_sess=2, nminibatches=paralelo) 
    #, max_grad_norm=1)
    #model = PPO2(CnnLstmPolicy, env1, verbose=1, n_steps=batch, n_cpu_tf_sess=2, nminibatches=paralelo)

model.learn(total_timesteps=updates*batch*paralelo)


In [ ]:
#import pickle

model.save(file+'II', cloudpickle=True)
param_list=model.get_parameter_list()
param=model.get_parameters()

f = open(file+'II_param.pkl',"wb")
#pickle.dump(param_list,f)
pickle.dump(param,f)
f.close()

In [ ]:
env1.close()

In [ ]:
#model = PPO2.load('ppo2_v0_mike_cnn')
#model.set_env(env2)


In [ ]:
# Enjoy trained agent
env2 = gym.make(agent)

if paralelo==1:
    obs=env2.reset()
else:
    import numpy as np
    obs=np.empty([paralelo,96,96,3])
    for i in range(paralelo):
        obs[i,:,:,:] = env2.reset()

        
done = False
pasos = 0
_states=None

while not done and pasos<1000:
    action, _states = model.predict(obs,_states)
    obs, reward, done, info = env2.step(action)
    env2.render()
    pasos+=1

    
env2.close()

In [ ]:
print(reward, done, info, pasos)

In [ ]:
print(action, _states)

In [ ]:
obs.shape

In [ ]:
env2.close()